### ISSUE TITLE
Liquid bottler only holds 100kg

### ISSUE THREAD

**Issue by rainbowdesign** [MooreDavid/ONI-MOD-#4]
thats bad when i have dupes with a carry capacity 1000+ better would be a capacity that is not so easy reached maybe 2000kg

**Comment by MooreDavid** [comment]
Changed and tested

**Comment by rainbowdesign** [comment]
Actually with the version i have now ( the recent for qol) its 100kg only.

**Comment by MooreDavid** [comment]
yes, it's because your dupes will not touch it unless it's full.

**Comment by rainbowdesign** [comment]
Yea but it is stupid to have the same guy run 3 to 10 times to fill a building with water while he can carry 1000kg only the bottler does not its inefficient.
And for it being filled dupes tend only take as much water they need, if there is more need in the colony build 2 bottler with 2 different pipes.
Also my high pressure mod has 400kg pipe capacity... However at some point i understand it. I will ask trevice if i can manipulate it with the building modifier.
